# Data-driven Reynolds stress modeling with physics-informed machine learning

Jinlong Wu, Carlos Michelén-Ströfer, Jianxun Wang, Heng Xiao


A complex physical system characterized by a wide range of temporal and spatial scales, turbulence is among the last unsolved problems in classical physics that affects natural and engineered systems from sub-meter to planetary scales. Current simulations of turbulent flows rely on Reynolds Averaged Navier Stokes equations with closure models.  In light of the decades-long stagnation in traditional turbulence modeling, we proposed data-driven, physics-informed machine learning method for turbulence modeling.

This repository contains tutorial Python scripts used to generated results published in the <<Wang2017Physics>> and <<Wu2018Data>>.

You can download the Jupyter Notebook to run and play with the code, or simply download the HTML version of the tutorial](regressionSolver.html) generated by the Jupyter Notebook.

Please send bug reports and comments to: Heng Xiao (hengxiao@vt.edu) +


[bibliography]
References
----------

[bibliography]

- [[[Wang2017Physics]]] J.-X. Wang, J.-L. Wu, and H. Xiao. Physics informed machine learning approach for reconstructing Reynolds stress modeling discrepancies based on DNS data. Physical Review Fluids. 2(3), 034603, 1-22, 2017. https://doi.org/10.1103/PhysRevFluids.2.034603[DOI:10.1103/PhysRevFluids.2.034603]

- [[[Wu2018Data]]] J.-L. Wu, H. Xiao and E. G. Paterson. Physics-informed machine learning approach for augmenting turbulence models: A comprehensive framework. Physical Review Fluids. 3, 074602, 1-28, 2018. DOI: 10.1103/PhysRevFluids.3.074602 

- [[[Wu2018Representation]]] J.-L. Wu, R. Sun, S. Laizet and H. Xiao. Representation of Reynolds stress perturbations with application in machine-learning-assisted turbulence modeling. Computer Methods in Applied Mechanics and Engineering. In Press, 2018. DOI: 10.1016/j.cma.2018.09.010 
