# Data-driven Reynolds stress modeling with physics-informed machine learning

Jinlong Wu, Carlos Michelén-Ströfer, Dr. Jianxun Wang, Heng Xiao


A complex physical system characterized by a wide range of temporal and spatial scales, turbulence is among the last unsolved problems in classical physics that affects natural and engineered systems from sub-meter to planetary scales. Current simulations of turbulent flows rely on Reynolds Averaged Navier Stokes equations with closure models.  In light of the decades-long stagnation in traditional turbulence modeling, we proposed data-driven, physics-informed machine learning method for turbulence modeling.

This repository contains tutorial Python scripts used to generated results published in the <<Wang2017Physics>> and <<Wu2018Data>>.

You can download the Jupyter Notebook to run and play with the code, or simply download or view [the HTML version of the tutorial](./regressionSolver.html) generated by the Notebook. 

Please send bug reports and comments to: Heng Xiao (hengxiao@vt.edu) +


[bibliography]
References
----------

[bibliography]

- [[[Wang2017Physics]]] J.-X. Wang, J.-L. Wu, and H. Xiao. Physics informed machine learning approach for reconstructing Reynolds stress modeling discrepancies based on DNS data. Physical Review Fluids. 2(3), 034603, 1-22, 2017. https://doi.org/10.1103/PhysRevFluids.2.034603[DOI:10.1103/PhysRevFluids.2.034603]

- [[[Wu2018Data]]] J.-L. Wu, H. Xiao and E. G. Paterson. Data-driven augmentation of turbulence models with physics-informed machine learning. Submitted, 2018. Also available at:  https://arxiv.org/abs/1801.02762[arXiv:1801.02762] Note: Part of this manuscript is presented in <<Wang2017Comprehensive>>.

- [[[Wang2017Comprehensive]]] Wang, Jian-Xun, Jinlong Wu, Julia Ling, Gianluca Iaccarino, and Heng Xiao. “A Comprehensive Physics-Informed Machine Learning Framework for Predictive Turbulence Modeling.” ArXiv:1701.07102  http://arxiv.org/abs/1701.07102[arXiv:1701.07102]
